# Docker Swarm Stack file
services:
  greeting-service:
    image: tsongpon/greeting-service:0.0.7
    environment:
      - OTEL_SERVICE_NAME=greeting-service
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.name=greeting-service,service.instance.id={{.Task.Name}},env=dev
      - OTEL_METRIC_EXPORT_INTERVAL=500
      - OTEL_BSP_SCHEDULE_DELAY=500
      - OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION=explicit_bucket_histogram
      - OTEL_SEMCONV_STABILITY_OPT_IN=http
    deploy:
      replicas: 2
      update_config:
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - core-infra

networks:
  core-infra:
    external: true
